# Generated by Django 4.1.3 on 2022-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proyecto')),
            ],
        ),
    ]
